#!/bin/bash


rsync -avP zims/content/wikipedia_en_for_schools_opt_2013* /library/zims/content/
rsync -avP zims/content/wikipedia_es_all_2015-10* /library/zims/content/
rsync -avP zims/content/wikispecies_en_all_2015-10* /library/zims/content/
rsync -avP zims/content/wiktionary_es_all_2015-10* /library/zims/content/

rsync -avP zims/index/wikipedia_en_for_schools_opt_2013.zim.idx /library/zims/index/
rsync -avP zims/index/wikipedia_es_all_2015-10.zim.idx /library/zims/index/
rsync -avP zims/index/wikispecies_en_all_2015-10.zim.idx /library/zims/index/
rsync -avP zims/index/wiktionary_es_all_2015-10.zim.idx /library/zims/index/
